# Generated by Django 4.2.1 on 2024-03-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='alternative_mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='other_field',
            field=models.FileField(blank=True, null=True, upload_to='contact_files'),
        ),
        migrations.AddField(
            model_name='contact',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='personal_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='contact_pictures'),
        ),
        migrations.AddField(
            model_name='contact',
            name='present_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
